'''https://www.logos.com/bible-book-abbreviations'''

bible = {
    'gen ge gn':'genesis',
    'ex exod exo':'exodus',
    'lev le lv lu leu leuiticus':'leviticus',
    'num nu nm nb':'numbers',
    'deut de dt':'deuteronomy',
    'josh iosh jos ios jsh ish ioshua':'joshua',
    'judg jdg jg jdgs iudg idg ig idgs iudges': 'judges',
    'ruth rth ru':'ruth',
    'samuell sam sm':'samuel',
    'kin king':'kings',
    'chron chr ch':'chronicles',
    'ezr ez':'ezra',
    'neh ne':'nehemiah',
    'esther':'est esth es',
    'job jb iob ib':'job',
    'ps psalm pslm psa psm pss psal':'psalms',
    'prov pro prv pr prou pru prouerb prouerbs':'proverbs',
    'eccles eccle ecc ec qoh':'ecclesiastes',
    'cant cantic canticle cantica':'canticles',
    'isa isai isay esa esai esay esaiae':'isaiah',
    'jer je jr ier ie ir ieremiah ierem':'jeremiah',
    'lam la lament':'lamentations',
    'ezek eze ezk ezech':'ezekiel',
    'dan da dn':'daniel',
    'hos ho':'hosea',
    'jl ioel il':'joel',
    'am':'amos',
    'obad ob':'obadiah',
    'jnh jon ion inh ionah':'jonah',
    'mic mc':'micah',
    'na nah':'nahum',
    'hab hb':'habakkuk',
    'zeph zep zp':'zephaniah',
    'hag hg':'haggai',
    'zech zec zc':'zechariah',
    'mal ml':'malachi',
    'matt matth mt math mat':'matthew',
    'mrk mar mk mr':'mark',
    'luk lk luc lc':'luke',
    'joh jhn ioh ihn iohn':'john',
    'act ac acta':'acts',
    'rom ro rm':'romans',
    'cor co':'corinthians',
    'gal ga':'galatians',
    'eph ephes ephe':'ephesians',
    'phil php pp phillip':'philippians',
    'col coloss':'colossians',
    'thess thes th':'thessalonians',
    'tim ti':'timothy',
    'tit ti':'titus',
    'philem phm pm':'philemon',
    'heb hebr':'hebrews',
    'jas jm iam ias im iames':'james',
    'pet pe pt p':'peter',
    'jud jd iud id iude':'jude',
    'rev re reu reuelation reuel reuelations':'revelation',
    'apoc': 'apocrypha',
    'tob tobi':'tobit',
    'jth jdth jdt ith idth idt iudith':'judith',
    'ecclus':'ecclesiasticus',
    'bar':'baruch',
    'epist':'epistle',
    }

numBook = {
    '1 samuel':'onesamuel',
    '2 samuel':'twosamuel',
    '1 kings':'onekings',
    '2 kings':'twokings',
    '1 chronicles':'onechronicles',
    '2 chronicles':'twochronicles',
    '1 corinthians':'onecorinthians',
    '2 corinthians':'twocorinthians',
    '1 thessalonians':'onethessalonians',
    '2 thessalonians':'twothessalonians',
    '1 timothy':'onetimothy',
    '2 timothy':'twotimothy',
    '1 peter':'onepeter',
    '2 peter':'twopeter',
    '1 john':'onejohn',
    '2 john':'twojohn',
    '3 john':'threejohn'
}

